name: Tests

on:
  push:
    branches:
      - main

jobs:
  
  runs-on: ubuntu-latest

  python:
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup
        id: setup
        run: bash ./submission/setup.sh

      - name: Install poetry
        run: pipx install poetry
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'poetry'
          cache-dependency-path: './poetry.lock'
          architecture: x64

      - name: Install poetry dependencies
        run: poetry install

      - black:
        id: black
        run: cd python && poetry run poe format --check-verbose && cd ..

      - pylint:
        id: lint
        run: cd python && poetry run poe lint && cd ..

      - name: What is the hash of block 654,321 (python)?
        run: |
          output=$(cd python && poetry run poe submission_001 && cd..)
          if [[ $output == "000000000000000000058452bbe379ad4364fe8fda68c45e299979b492858095" ]]; then
            exit 0
          else
            exit 1
          fi
