name: Tests

on:
  push:
    branches:
      - main

jobs:
  
  python:
  
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup
        id: setup
        run: bash ./submission/setup.sh

      - name: Install poetry
        run: pipx install poetry
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'poetry'
          cache-dependency-path: './submission_in_python/poetry.lock'
          architecture: x64

      - name: Install poetry dependencies
        working-directory: ./submission_in_python
        run: poetry install

      - name: Black
        working-directory: ./submission_in_python
        run: poetry run poe format --check-verbose

      - name: Pylint
        working-directory: ./submission_in_python
        run: poetry run poe lint
      
      - name: Pytest
        working-directory: ./submission_in_python
        run: poetry run poe test

  rust:
    
    runs-on: ubuntu-latest
    
    steps:  
      
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup
        id: setup
        run: bash ./submission/setup.sh

      - name: Setup rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        
      - name: Build
        working-directory: ./submission_in_rust
        run: cargo test
